steps:
  # Install backend dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'backend'

  # Install frontend dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Build the frontend
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'

  # Install firebase-tools in the root
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', 'firebase-tools']

  # Deploy both functions and hosting to Firebase
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['firebase', 'deploy', '--only', 'functions,hosting', '--project', '$PROJECT_ID', '--force']
options:
  logging: CLOUD_LOGGING_ONLY
