import React,
{
    createContext,
    useState,
    useContext,
    ReactNode
} from 'react';

const translations = {
    en: {
        "welcome_title": "Welcome to Save TaiPo",
        "welcome_subtitle": "We connect community to help each other during emergencies. Let's get you set up.",
        "welcome_resident_title": "Welcome.",
        "resident_points": "This app helps you quickly find nearby shelters and supply points. You can use the map and filter by the type of support you need (for example warm clothing, food, power banks, or pet support), and you can also browse curated useful links and other platforms.",
        "welcome_volunteer_title": "Thank you for stepping up to help.",
        "volunteer_points": "This app shows you, in real time, which locations need supplies or manpower, and you can filter by the types of items you have so you know exactly where they’re needed. You can also open the useful links area to quickly access Telegram groups and other platforms.",
        "welcome_driver_title": "Welcome Driver",
        "welcome_driver_subtitle": "Your vehicle can make a huge difference:",
        "driver_point_1": "Find Transport Tasks to move supplies.",
        "driver_point_2": "Accept tasks that fit your vehicle type and route.",
        "driver_points": "Find Transport Tasks to move supplies.\nAccept tasks that fit your vehicle type and route.",
        "welcome_station_manager_title": "Welcome Station Manager",
        "welcome_station_manager_subtitle": "You are key to your station's success:",
        "station_manager_point_1": "Manage your station's details, status, and inventory.",
        "station_manager_point_2": "Create tasks for your station team.",
        "station_manager_point_3": "Broadcast alerts to residents.",
        "station_manager_points": "Manage your station's details, status, and inventory.\nCreate tasks for your station team.\nBroadcast alerts to residents.",
        "welcome_admin_title": "Welcome Admin",
        "welcome_admin_subtitle": "System Overview:",
        "admin_point_1": "Manage all users, stations, and tasks.",
        "admin_point_2": "Review analytics and system health.",
        "admin_point_3": "Handle high-level configurations and alerts.",
        "admin_points": "Manage all users, stations, and tasks.\nReview analytics and system health.\nHandle high-level configurations and alerts.",
        "get_started": "Get Started",
        "next": "Next",
        "back": "Back",
        "what_brings_you_here": "What brings you here?",
        "i_need_help": "I need help",
        "find_supplies": "Find supplies, stations, and support nearby.",
        "or_i_want_to_help": "OR I WANT TO HELP",
        "i_want_to_volunteer": "I want to Volunteer",
        "join_teams": "Join teams, help at stations, and assist others.",
        "i_am_a_driver": "I am a Driver",
        "help_transport": "Help transport supplies between stations.",
        "back_to_role_selection": "Back to role selection",
        "add.title": "Add New Station",
        "add.name": "Station Name",
        "add.placeholder_name": "e.g., Tai Po Community Hall",
        "add.address": "Address",
        "add.placeholder_address": "Enter address or use map",
        "add.type": "Station Type",
        "add.contact": "Contact Number",
        "add.placeholder_contact": "Optional phone number",
        "add.contact_link": "Contact Link",
        "add.placeholder_contact_link": "Optional URL (e.g., Telegram, WhatsApp)",
        "add.source_url": "Source URL",
        "add.placeholder_source": "Link to the source of information",
        "btn.submit": "Submit Station",
        "btn.deselect_all": "Deselect All",
        "btn.select_all": "Select All",
        "btn.clear": "Clear",
        "btn.apply": "Apply",
        "btn.add_item": "Add a new item",
        "validation.enter_item": "Please enter an item name.",
        "validation.no_category": "Please select a category.",
        "validation.already_exists": "This item already exists.",
        "btn.add": "Add",
        "btn.add_category": "Add a new category",
        "validation.enter_category": "Please enter a category name.",
        "status.available": "Available",
        "status.available.volunteer": "Enough",
        "status.available.resident": "Enough",
        "status.low_stock": "Low Stock",
        "status.low_stock.volunteer": "Still Need",
        "status.low_stock.resident": "Small Amount",
        "status.urgent": "Urgent",
        "status.urgent.volunteer": "Urgent",
        "status.urgent.resident": "Shortage",
        "status.no_data": "No Data",
        "status.no_data.volunteer": "No Data",
        "status.no_data.resident": "No Data",
        "status.gov_control": "Gov has taken control",
        "status.gov_control.volunteer": "Gov has taken control (no volunteer items needed)",
        "status.gov_control.resident": "No Data",
        "status.paused": "Paused (on-site only)",
        "status.paused.volunteer": "Paused (on-site only)",
        "status.paused.resident": "No Data",
        "auth.login_required": "Please log in to perform this action.",
        "vote.success": "Vote submitted successfully.",
        "vote.error": "Failed to submit vote.",
        "favorite.added": "Added to favorites.",
        "favorite.removed": "Removed from favorites.",
        "res.my_location": "My Location",
        "status.unverified": "Unverified",
        "card.offerings": "Offerings",
        "card.no_info": "No information",
        "res.view_details": "View Details",
        "res.search_placeholder": "Search stations or items",
        "type.all": "All",
        "res.more_filters": "More Filters",
        "btn.filter_items": "Filter by Resources",
        "sort.status": "Sort by Status",
        "sort.distance_disabled": "Enable location to sort by distance",
        "sort.distance": "Sort by Distance",
        "btn.reset": "Reset",
        "res.filter_pets": "Pet-Friendly",
        "res.filter_baby": "Baby Care",
        "res.filter_wheelchair": "Wheelchair Accessible",
        "res.filter_charging": "Charging Available",
        "btn.traffic": "Toggle Traffic",
        "res.no_stations_map": "No stations match your filters.",
        "common.loading": "Loading...",
        "res.no_stations_list": "No stations found.",
        "res.filter_title": "Filter by Resources",
        "nav.resident": "Resident",
        "nav.links": "Links",
        "nav.me": "Me",
        "nav.my_stations": "My Stations",
        "nav.volunteer": "Volunteer",
        "nav.logistics": "Logistics",
        "me.title": "My Profile",
        "role.volunteer": "Volunteer",
        "role.resident": "Resident",
        "me.switch_role": "Switch Role",
        "station.managed_station_id": "Managed Station ID",
        "btn.signout": "Sign Out",
        "me.login_desc": "Log in to save favorites and contribute.",
        "btn.signin": "Sign In with Google",
        "btn.continue_without_login": "Continue without login",
        "onboarding.logged_in_features.title": "Extra features if you sign in",
        "onboarding.logged_in_features.desc": "Sign in to save favorites and like / dislike stations ",
        "onboarding.location_title": "Enable location to find nearby help",
        "onboarding.location_desc": "We use your location to show nearby stations and route directions. You can enable location now or choose to allow it later.",
        "onboarding.location_allow": "Allow Location",
        "onboarding.location_maybe_later": "Maybe later",
        "btn.skip": "Skip",
        "admin.global_alert_broadcast": "Global Alert Broadcast",
        "admin.alert_placeholder": "Enter a global alert message",
        "admin.publish_alert": "Publish Alert",
        "me.my_stations": "My Stations",
        "me.saved_stations": "Saved Stations",
        "me.no_saved": "You haven't saved any stations yet.",
        "btn.directions": "Directions",
        "btn.favorite": "Favorite",
        "btn.call": "Call",
        "btn.contact": "Contact",
        "station.needs_label": "Needs",
        "station.remarks_label": "Remarks",
        "station.offerings_label": "Offerings",
        "station.login_to_view": "Please log in to view your stations.",
        "station.edit_station": "Edit Station",
        "btn.save": "Save",
        "station.name": "Station Name",
        "station.address_location": "Address & Location",
        "station.use_current_location": "Use Current Location",
        "station.hide_map": "Hide Map",
        "station.pick_on_map": "Pick on Map",
        "station.map_helper_text": "Drag marker or click to set location",
        "station.status": "Status",
        "station.add_needs": "Add Needs",
        "btn.save_changes": "Save Changes",
        "btn.cancel": "Cancel",
        "station.manage_desc": "Manage your station's details, status, and inventory.",
        "btn.edit": "Edit",
        "station.no_owned_stations": "You do not own or manage any stations.",
        "station.create_station_prompt": "Create a new station to get started.",
        "links.tg_title": "Telegram Groups",
        "links.web_title": "Websites",
        "type.supply": "Supply",
        "type.shelter": "Shelter",
        "type.closed": "Closed",
        "type.pet_shelter": "Pet Shelter",
        "type.food_distribution": "Food",
        "type.medical": "Medical",
        "type.collection_point": "Collection",
        "crowd.low": "Low",
        "crowd.medium": "Medium",
        "crowd.high": "High",
        "crowd.full": "Full",
        "FOOD": "Food",
        "DRINKS": "Drinks",
        "MEDICAL_SUPPLIES": "Medical Supplies",
        "HYGIENE": "Hygiene",
        "CLOTHING": "Clothing",
        "BABY_CARE": "Baby Care",
        "PET_SUPPLIES": "Pet Supplies",
        "ELECTRONICS": "Electronics",
        "SHELTER": "Shelter",
        "SERVICES": "Services",
        "favorite.update_failed": "Failed to update favorite",
        "volunteer.data_load_error": "Failed to load volunteer data",
        "volunteer.unknown_station": "Unknown Station",
        "volunteer.task_claimed": "Task claimed!",
        "volunteer.claim_failed": "Failed to claim task",
        "volunteer.confirm_completion": "Confirm delivery completion?",
        "volunteer.task_completed": "Task completed!",
        "volunteer.complete_failed": "Failed to complete task",
        "volunteer.tasks": "Tasks",
        "volunteer.stations": "Stations",
        "volunteer.help_community": "Help your community",
        "volunteer.open_tasks": "Open Tasks",
        "volunteer.my_tasks": "My Tasks",
        "volunteer.my_active_tasks": "Your Active Tasks",
        "volunteer.in_progress": "IN PROGRESS",
        "volunteer.complete": "Complete",
        "volunteer.available_tasks": "Available Tasks",
        "volunteer.no_tasks": "No tasks currently available.",
        "volunteer.posted": "Posted",
        "volunteer.from": "From",
        "volunteer.to": "To",
        "volunteer.volunteer_for_task": "Volunteer for this Task",
        
        // Categories
        "cat.manpower": "Manpower",
        "cat.warmth": "Warmth",
        "cat.food_water": "Food & Water",
        "cat.hygiene_wash": "Hygiene & Wash",
        "cat.electronics": "Electronics",
        "cat.bedding": "Bedding",
        "cat.sanitary": "Sanitary",
        "cat.pets": "Pet Supplies",
        "cat.baby": "Baby Supplies",
        "cat.others": "Others",
        "me.switch_guest_resident": "Switch to Resident (guest)",
        "me.switch_guest_volunteer": "Switch to Volunteer (guest)",
        "confirm.guest_switch_resident": "Switching to Resident mode will change the app view for guests. Continue?",
        "confirm.guest_switch_volunteer": "Switching to Volunteer mode will change the app view for guests. Continue?",
        "organizer.gov": "Gov",
        "organizer.ngo": "NGO",
        "organizer.community": "Community",
        "filter.organizer": "Organizer",

        // Items
        "一般義工": "Volunteers",
        "醫護人員": "Medic",
        "社工": "Social Worker",
        "車手": "Driver",
        "心理輔導員": "Psychological Counselor",
        "保暖內衣": "Thermal Underwear",
        "求毛氈": "Blanket",
        "反光錫紙": "Reflective Foil",
        "熱水": "Hot Water",
        "水": "Water",
        "麵包": "Bread",
        "能量啫喱": "Energy Gel",
        "大毛巾": "Large Towel",
        "洗頭水": "Shampoo",
        "沐浴露": "Body Wash",
        "垃圾袋": "Trash Bag",
        "摺凳": "Folding Stool",
        "番梘": "Soap",
        "尿袋": "Power Bank",
        "照明用品": "Lighting",
        "差電線": "Charging Cable",
        "床墊": "Mattress",
        "枕頭": "Pillow",
        "被": "Quilt",
        "眼罩": "Eye Mask",
        "耳塞": "Earplugs",
        "75%支裝酒精": "75% Alcohol",
        "濕紙巾": "Wet Wipes",
        "女性用品": "Feminine Hygiene",
        "貓狗罐頭": "Pet Canned Food",
        "貓狗乾糧": "Pet Dry Food",
        "寵物衣服": "Pet Clothes",
        "藥品": "Medicine",
        "奶樽": "Baby Bottle",
        "奶粉": "Milk Powder",
        "尿片": "Diapers",
        "文具": "Stationery",
        "紅白藍膠袋": "RB Bag",
        "大聲公": "Megaphone",
        
        // Old items kept for compatibility
        "住宿": "Accommodation",
        "暫住": "Temporary Shelter",
        "宿位": "Beds",
        "庇護中心": "Shelter Center",
        "休息處": "Rest Area",
        "洗澡設施": "Shower Facilities",
        "洗手間": "Toilets",
        "水機": "Water Dispenser",
        "廚房": "Kitchen",
        "食物": "Food",
        "飲品": "Drinks",
        "樽裝水": "Bottled Water",
        "乾糧": "Dry Food",
        "杯麵": "Cup Noodles",
        "熱食": "Hot Food",
        "能量棒": "Energy Bar",
        "湯水": "Soup",
        "罐頭": "Canned Food",
        "餐具": "Cutlery",
        "飯盒": "Lunch Box",
        "紙杯": "Paper Cup",
        "保暖物資": "Warmth Supplies",
        "毛巾": "Towel",
        "毛氈": "Blanket",
        "被鋪": "Bedding",
        "褸": "Coat",
        "襪": "Socks",
        "暖包": "Heat Pack",
        "睡袋": "Sleeping Bag",
        "地墊": "Mat",
        "露營帳篷": "Tent",
        "Heat tech": "Heat Tech",
        "牙刷": "Toothbrush",
        "牙膏": "Toothpaste",
        "口罩": "Mask",
        "豬咀": "Gas Mask",
        "濾罐": "Filter",
        "BB尿片": "Baby Diapers",
        "成人尿片": "Adult Diapers",
        "清潔用品": "Cleaning Supplies",
        "紙巾": "Tissue",
        "一次性內衣褲": "Disposable Underwear",
        "拖鞋": "Slippers",
        "內衣褲": "Underwear",
        "衛生用品": "Sanitary Supplies",
        "N95": "N95 Mask",
        "叉電線": "Charging Cable",
        "火牛": "Adapter",
        "拖板": "Power Strip",
        "電池": "Battery",
        "電筒": "Flashlight",
        "SIM Card": "SIM Card",
        "急救": "First Aid",
        "急救包": "First Aid Kit",
        "輪椅": "Wheelchair",
        "寵物氧氣機": "Pet Oxygen Machine",
        "寵物飛機籠": "Pet Crate",
        "寵物暫托家庭": "Pet Foster Home",
        "貓糧": "Cat Food",
        "狗糧": "Dog Food",
        "獸醫服務": "Vet Service",
        "寵物救援": "Pet Rescue",
        "看顧長者": "Elderly Care",
        "兒童暫託": "Child Care",
        "心理支援": "Psychological Support"
    },
    zh: {
        "welcome_title": "大埔救急 Save TaiPo",
        "welcome_subtitle": "一個為大埔宏福苑五級火災緊急救援同整合物資狀態而設嘅平臺，確保每份民間力量都用得其所",
        "welcome_resident_title": "你好",
        "resident_points": "你可以用呢個app去搵最近嘅物資站同庇護中心，亦可以filter自己需要嘅資源類型（例如保暖物資、食物、尿袋、寵物支援）。\n你亦都可以睇到整理好嘅links同求助資訊。",
        "welcome_volunteer_title": "你好",
        "volunteer_points": "多謝你出一分力。你可以用呢個app實時睇到各個物資站需要咩物資或者人手，再用filter返你手上有嘅物資。\n你亦都可以搵到整理好嘅其他平台links同各個TG群組。",
        "welcome_driver_title": "歡迎",
        "welcome_driver_subtitle": "您的車輛可以發揮巨大作用：",
        "driver_point_1": "尋找運輸任務以運送物資。",
        "driver_point_2": "接受適合您車型和路線的任務。",
        "driver_points": "尋找運輸任務以運送物資。\n接受適合您車型和路線的任務。",
        "welcome_station_manager_title": "歡迎站長",
        "welcome_station_manager_subtitle": "您是您物資站成功的關鍵：",
        "station_manager_point_1": "管理您物資站的詳細資訊、狀態和庫存。",
        "station_manager_point_2": "為您的物資站團隊創建任務。",
        "station_manager_point_3": "向居民廣播警報。",
        "station_manager_points": "管理您物資站的詳細資訊、狀態和庫存。\n為您的物資站團隊創建任務。\n向居民廣播警報。",
        "welcome_admin_title": "歡迎",
        "welcome_admin_subtitle": "系統概覽：",
        "admin_point_1": "管理所有使用者、物資站和任務。",
        "admin_point_2": "查看分析和系統健康狀況。",
        "admin_point_3": "處理高層級配置和警報。",
        "admin_points": "管理所有使用者、物資站和任務。\n查看分析和系統健康狀況。\n處理高層級配置和警報。",
        "get_started": "開始",
        "next": "下一步",
        "back": "返回",
        "what_brings_you_here": "您嚟呢度想做咩？",
        "i_need_help": "我要搵物資",
        "find_supplies": "搵附近嘅物資站同支援。",
        "or_i_want_to_help": "或者我想幫手",
        "i_want_to_volunteer": "我想幫手",
        "join_teams": "支援大埔宏福苑火災影響嘅街坊",
        "i_am_a_driver": "我係車手",
        "help_transport": "幫助在物資站之間運輸物資。",
        "back_to_role_selection": "返回",
        "add.title": "新增物資站",
        "add.name": "物資站名稱",
        "add.placeholder_name": "例如：大埔社區會堂",
        "add.address": "地址",
        "add.placeholder_address": "輸入地址或使用地圖",
        "add.type": "物資站類型",
        "add.contact": "聯絡電話",
        "add.placeholder_contact": "可選電話號碼",
        "add.contact_link": "聯絡連結",
        "add.placeholder_contact_link": "可選 URL（例如：Telegram、WhatsApp）",
        "add.source_url": "資訊來源 URL",
        "add.placeholder_source": "資訊來源連結",
        "btn.submit": "提交物資站",
        "btn.deselect_all": "全部取消",
        "btn.select_all": "全選",
        "btn.clear": "清除",
        "btn.apply": "套用",
        "btn.add_item": "新增一個新項目",
        "validation.enter_item": "請輸入項目名稱。",
        "validation.no_category": "請選擇一個類別。",
        "validation.already_exists": "此項目已存在。",
        "btn.add": "新增",
        "btn.add_category": "新增一個新類別",
        "validation.enter_category": "請輸入類別名稱。",
        "status.available": "充足",
        "status.low_stock": "尚需",
        "status.low_stock.volunteer": "尚需",
        "status.low_stock.resident": "少量",
        "status.available.volunteer": "充足",
        "status.available.resident": "充足",
        "status.urgent": "急需",
        "status.urgent.volunteer": "急需",
        "status.urgent.resident": "短缺",
        "status.no_data": "無資料",
        "status.no_data.volunteer": "無資料",
        "status.no_data.resident": "無資料",
        "status.gov_control": "政府已接手 (不需物資)",
        "status.gov_control.volunteer": "政府已接手（不需義工物資）",
        "status.gov_control.resident": "無資料",
        "status.paused": "暫停接收物資",
        "status.paused.volunteer": "暫停接收物資",
        "status.paused.resident": "無資料",
        "auth.login_required": "請登入以執行此操作。",
        "vote.success": "投票已成功提交。",
        "vote.error": "提交投票失敗。",
        "favorite.added": "已新增至我的最愛。",
        "favorite.removed": "已從我的最愛中移除。",
        "res.my_location": "我的位置",
        "status.unverified": "未驗證",
        "card.offerings": "提供",
        "card.no_info": "沒有資訊",
        "res.view_details": "查看詳情",
        "res.search_placeholder": "搜尋物資站或物品",
        "type.all": "全部",
        "res.more_filters": "更多篩選",
        "btn.filter_items": "按資源篩選",
        "sort.status": "按狀態排序",
        "sort.distance_disabled": "啟用定位以按距離排序",
        "sort.distance": "按距離排序",
        "btn.reset": "重設",
        "btn.traffic": "切換交通狀況",
        "res.no_stations_map": "沒有符合您篩選條件的物資站",
        "common.loading": "載入中...",
        "res.no_stations_list": "找不到物資站",
        "res.filter_title": "按資源篩選",
        "nav.resident": "物資站",
        "nav.links": "連結",
        "nav.me": "我的",
        "nav.my_stations": "我的物資站",
        "nav.volunteer": "幫手",
        "nav.logistics": "物流",
        "me.title": "我的個人資料",
        "role.volunteer": "義工",
        "role.resident": "居民",
        "me.switch_role": "切換模式",
        "me.switch_guest_resident": "切換到居民模式",
        "me.switch_guest_volunteer": "切換到義工模式",
        "confirm.guest_switch_resident": "切換到居民模式會更改畫面，繼續？",
        "confirm.guest_switch_volunteer": "切換到義工模式會更改畫面，繼續？",
        "organizer.gov": "政府",
        "organizer.ngo": "NGO",
        "organizer.community": "民間",
        "filter.organizer": "搞手",
        "station.managed_station_id": "管理的物資站 ID",
        "btn.signout": "登出",
        "me.login_desc": "登入以儲存我的最愛和貢獻。",
        "btn.signin": "使用 Google 登入",
        "btn.continue_without_login": "以訪客身份繼續",
        "btn.skip": "跳過",
        "onboarding.logged_in_features.title": "登入後可以：",
        "onboarding.logged_in_features.desc": "收藏同埋評價物資站",
        "onboarding.location_title": "開啟定位以尋找附近物資站",
        "onboarding.location_desc": "我哋會用你嘅位置幫你顯示附近有咩物資站。\n你可以而家允許定位，或者之後再喺設定入面開啟。",
        "onboarding.location_allow": "允許定位",
        "onboarding.location_maybe_later": "遲啲先算",
        "admin.global_alert_broadcast": "全域警報廣播",
        "admin.alert_placeholder": "輸入全域警報訊息",
        "admin.publish_alert": "發佈警報",
        "me.my_stations": "我的站點",
        "me.saved_stations": "已儲存的站點",
        "me.no_saved": "您尚未儲存任何站點。",
        "btn.directions": "路線",
        "btn.favorite": "收藏",
        "station.needs_label": "需求",
        "station.remarks_label": "備註",
        "station.offerings_label": "提供",
        "station.login_to_view": "請登入以查看您的物資站。",
        "station.edit_station": "編輯物資站",
        "btn.call": "致電",
        "btn.contact": "聯絡",
        "btn.save": "儲存",
        "station.name": "物資站名稱",
        "station.address_location": "地址和位置",
        "station.use_current_location": "使用目前位置",
        "station.hide_map": "隱藏地圖",
        "station.pick_on_map": "在地圖上選擇",
        "station.map_helper_text": "拖曳標記或點擊以設定位置",
        "station.status": "狀態",
        "station.add_needs": "新增需求",
        "btn.save_changes": "儲存變更",
        "btn.cancel": "取消",
        "station.manage_desc": "管理您物資站的詳細資訊、狀態和庫存。",
        "btn.edit": "編輯",
        "station.no_owned_stations": "您沒有擁有或管理任何物資站。",
        "station.create_station_prompt": "建立一個新物資站以開始。",
        "links.tg_title": "Telegram 群組",
        "links.web_title": "網站",
        "type.supply": "物資站",
        "type.shelter": "住宿/庇護",
        "type.closed": "已清場",
        "type.pet_shelter": "寵物庇護所",
        "type.food_distribution": "食物",
        "type.medical": "醫療",
        "type.collection_point": "收集點",
        "crowd.low": "低",
        "crowd.medium": "中",
        "crowd.high": "高",
        "crowd.full": "滿",
        "FOOD": "食物",
        "DRINKS": "飲品",
        "MEDICAL_SUPPLIES": "醫療用品",
        "HYGIENE": "衛生用品",
        "CLOTHING": "衣物",
        "BABY_CARE": "嬰兒用品",
        "PET_SUPPLIES": "寵物用品",
        "ELECTRONICS": "電子產品",
        "SHELTER": "住宿/庇護",
        "SERVICES": "服務",
        "favorite.update_failed": "更新我的最愛失敗",
        "volunteer.data_load_error": "載入志願者資料失敗",
        "volunteer.unknown_station": "未知物資站",
        "volunteer.task_claimed": "已領取任務！",
        "volunteer.claim_failed": "領取任務失敗",
        "volunteer.confirm_completion": "確認完成運送？",
        "volunteer.task_completed": "任務已完成！",
        "volunteer.complete_failed": "完成任務失敗",
        "volunteer.tasks": "任務",
        "volunteer.stations": "物資站",
        "volunteer.help_community": "幫助您的社區",
        "volunteer.open_tasks": "開放任務",
        "volunteer.my_tasks": "我的任務",
        "volunteer.my_active_tasks": "您目前的任務",
        "volunteer.in_progress": "進行中",
        "volunteer.complete": "完成",
        "volunteer.available_tasks": "可領取的任務",
        "volunteer.no_tasks": "目前沒有可領取的任務。",
        "volunteer.posted": "發佈於",
        "volunteer.from": "從",
        "volunteer.to": "到",
        "volunteer.volunteer_for_task": "為此任務擔任志願者",

        // Categories
        "cat.manpower": "人手支援",
        "cat.warmth": "保暖用品",
        "cat.food_water": "糧食&水",
        "cat.hygiene_wash": "梳洗用品",
        "cat.electronics": "電器",
        "cat.bedding": "寢室用品",
        "cat.sanitary": "衛生用品",
        "cat.pets": "寵物用品",
        "cat.baby": "BB用品",
        "cat.others": "其他",

        // Items
        "一般義工": "義工",
        "醫護人員": "醫護人員",
        "社工": "社工",
        "車手": "車手",
        "心理輔導員": "心理輔導員",
        "保暖內衣": "保暖內衣",
        "求毛氈": "求毛氈",
        "反光錫紙": "反光錫紙",
        "熱水": "熱水",
        "水": "水",
        "麵包": "麵包",
        "能量啫喱": "能量啫喱",
        "大毛巾": "大毛巾",
        "洗頭水": "洗頭水",
        "沐浴露": "沐浴露",
        "垃圾袋": "垃圾袋",
        "摺凳": "摺凳",
        "番梘": "番梘",
        "尿袋": "尿袋",
        "照明用品": "照明用品",
        "差電線": "差電線",
        "床墊": "床墊",
        "枕頭": "枕頭",
        "被": "被",
        "眼罩": "眼罩",
        "耳塞": "耳塞",
        "75%支裝酒精": "75%支裝酒精",
        "濕紙巾": "濕紙巾",
        "女性用品": "女性用品",
        "貓狗罐頭": "貓狗罐頭",
        "貓狗乾糧": "貓狗乾糧",
        "寵物衣服": "寵物衣服",
        "藥品": "藥品",
        "奶樽": "奶樽",
        "奶粉": "奶粉",
        "尿片": "尿片",
        "文具": "文具",
        "紅白藍膠袋": "紅白藍膠袋",
        "大聲公": "大聲公",
        
        // Old items kept for compatibility
        "住宿": "住宿",
        "暫住": "暫住",
        "宿位": "宿位",
        "庇護中心": "庇護中心",
        "休息處": "休息處",
        "洗澡設施": "洗澡設施",
        "洗手間": "洗手間",
        "水機": "水機",
        "廚房": "廚房",
        "食物": "食物",
        "飲品": "飲品",
        "樽裝水": "樽裝水",
        "乾糧": "乾糧",
        "杯麵": "杯麵",
        "熱食": "熱食",
        "能量棒": "能量棒",
        "湯水": "湯水",
        "罐頭": "罐頭",
        "餐具": "餐具",
        "飯盒": "飯盒",
        "紙杯": "紙杯",
        "保暖物資": "保暖物資",
        "毛巾": "毛巾",
        "毛氈": "毛氈",
        "被鋪": "被鋪",
        "褸": "褸",
        "襪": "襪",
        "暖包": "暖包",
        "睡袋": "睡袋",
        "地墊": "地墊",
        "露營帳篷": "露營帳篷",
        "Heat tech": "Heat tech",
        "牙刷": "牙刷",
        "牙膏": "牙膏",
        "口罩": "口罩",
        "豬咀": "豬咀",
        "濾罐": "濾罐",
        "BB尿片": "BB尿片",
        "成人尿片": "成人尿片",
        "清潔用品": "清潔用品",
        "紙巾": "紙巾",
        "一次性內衣褲": "一次性內衣褲",
        "拖鞋": "拖鞋",
        "內衣褲": "內衣褲",
        "衛生用品": "衛生用品",
        "N95": "N95",
        "叉電線": "叉電線",
        "火牛": "火牛",
        "拖板": "拖板",
        "電池": "電池",
        "電筒": "電筒",
        "SIM Card": "SIM Card",
        "急救": "急救",
        "急救包": "急救包",
        "輪椅": "輪椅",
        "寵物氧氣機": "寵物氧氣機",
        "寵物飛機籠": "寵物飛機籠",
        "寵物暫托家庭": "寵物暫托家庭",
        "貓糧": "貓糧",
        "狗糧": "狗糧",
        "獸醫服務": "獸醫服務",
        "寵物救援": "寵物救援",
        "看顧長者": "看顧長者",
        "兒童暫託": "兒童暫託",
        "心理支援": "心理支援"
    }
};

type Language = 'en' | 'zh';

interface LanguageContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({
    children
}: {
    children: ReactNode
}) => {
    const [language, setLanguage] = useState<Language>(() => {
            try {
                const saved = typeof window !== 'undefined' && localStorage.getItem('language');
                return (saved as Language) || 'zh';
            } catch (err) {
                return 'zh';
            }
        });

    const t = (key: keyof typeof translations.en) => {
        // Safe access across both languages – fall back to English if key is missing in selected language
        return ((translations as any)[language] as Record<string, string>)[key] || translations.en[key as keyof typeof translations.en];
    };

    const setLang = (lang: Language) => {
        setLanguage(lang);
        try {
            if (typeof window !== 'undefined') {
                localStorage.setItem('language', lang);
            }
        } catch (err) {
            // ignore localStorage errors
        }
        try {
            if (typeof window !== 'undefined') {
                window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
            }
        } catch (err) {
            // ignore
        }
    };

    React.useEffect(() => {
        if (typeof window === 'undefined') return;
        const handler = (ev: any) => {
            const lang = ev?.detail;
            if (lang && (lang === 'en' || lang === 'zh')) {
                setLang(lang as Language);
            }
        };
        window.addEventListener('languageChanged', handler);
        return () => window.removeEventListener('languageChanged', handler);
    }, []);

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage: setLang,
            t
        }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

// Listen for user-driven language defaults (from AuthContext)
if (typeof window !== 'undefined') {
    window.addEventListener('userPrefersLanguage', (ev: any) => {
        const lang = ev?.detail;
        if (lang && (lang === 'en' || lang === 'zh')) {
            // set and persist the language for the app
            try { localStorage.setItem('language', lang); } catch {}
            const event = new CustomEvent('languageChanged', { detail: lang });
            window.dispatchEvent(event);
        }
    });
}
