import React,
{
    createContext,
    useState,
    useContext,
    ReactNode
} from 'react';

const translations = {
    en: {
        "welcome_title": "Welcome to Tai Po Rescue",
        "welcome_subtitle": "We connect neighbors to help each other during emergencies. Let's get you set up.",
        "welcome_resident_title": "Welcome Resident",
        "welcome_resident_subtitle": "As a resident, you can:",
        "resident_point_1": "Find nearby stations for supplies and help.",
        "resident_point_2": "Stay updated on station statuses.",
        "resident_point_3": "Favorite stations for quick access.",
        "welcome_volunteer_title": "Welcome Volunteer",
        "welcome_volunteer_subtitle": "Your help is crucial. As a volunteer, you can:",
        "volunteer_point_1": "Join a Station Team to coordinate efforts.",
        "volunteer_point_2": "View and accept Tasks to help operations run smoothly.",
        "volunteer_point_3": "Update station statuses to keep residents informed.",
        "welcome_driver_title": "Welcome Driver",
        "welcome_driver_subtitle": "Your vehicle can make a huge difference:",
        "driver_point_1": "Find Transport Tasks to move supplies.",
        "driver_point_2": "Accept tasks that fit your vehicle type and route.",
        "welcome_station_manager_title": "Welcome Station Manager",
        "welcome_station_manager_subtitle": "You are key to your station's success:",
        "station_manager_point_1": "Manage your station's details, status, and inventory.",
        "station_manager_point_2": "Create tasks for your station team.",
        "station_manager_point_3": "Broadcast alerts to residents.",
        "welcome_admin_title": "Welcome Admin",
        "welcome_admin_subtitle": "System Overview:",
        "admin_point_1": "Manage all users, stations, and tasks.",
        "admin_point_2": "Review analytics and system health.",
        "admin_point_3": "Handle high-level configurations and alerts.",
        "get_started": "Get Started",
        "next": "Next",
        "back": "Back",
        "what_brings_you_here": "What brings you here?",
        "i_need_help": "I need help",
        "find_supplies": "Find supplies, stations, and support nearby.",
        "or_i_want_to_help": "OR I WANT TO HELP",
        "i_want_to_volunteer": "I want to Volunteer",
        "join_teams": "Join teams, help at stations, and assist others.",
        "i_am_a_driver": "I am a Driver",
        "help_transport": "Help transport supplies between stations.",
        "back_to_role_selection": "Back to role selection",
        "add.title": "Add New Station",
        "add.name": "Station Name",
        "add.placeholder_name": "e.g., Tai Po Community Hall",
        "add.address": "Address",
        "add.placeholder_address": "Enter address or use map",
        "add.type": "Station Type",
        "add.contact": "Contact Number",
        "add.placeholder_contact": "Optional phone number",
        "add.contact_link": "Contact Link",
        "add.placeholder_contact_link": "Optional URL (e.g., Telegram, WhatsApp)",
        "add.source_url": "Source URL",
        "add.placeholder_source": "Link to the source of information",
        "btn.submit": "Submit Station",
        "btn.deselect_all": "Deselect All",
        "btn.select_all": "Select All",
        "btn.clear": "Clear",
        "btn.apply": "Apply",
        "btn.add_item": "Add a new item",
        "validation.enter_item": "Please enter an item name.",
        "validation.no_category": "Please select a category.",
        "validation.already_exists": "This item already exists.",
        "btn.add": "Add",
        "btn.add_category": "Add a new category",
        "validation.enter_category": "Please enter a category name.",
        "status.available": "✅ Available",
        "status.low_stock": "⚠️ Low Stock",
        "status.urgent": "‼️ Urgent",
        "status.no_data": "🤨 No Data",
        "status.gov_control": "🙅🏻 Gov has taken control",
        "status.paused": "暫停接收物資（現場提供）",
        "auth.login_required": "Please log in to perform this action.",
        "vote.success": "Vote submitted successfully.",
        "vote.error": "Failed to submit vote.",
        "favorite.added": "Added to favorites.",
        "favorite.removed": "Removed from favorites.",
        "res.my_location": "My Location",
        "status.unverified": "Unverified",
        "card.offerings": "Offerings",
        "card.no_info": "No information",
        "res.view_details": "View Details",
        "res.search_placeholder": "Search stations or items",
        "type.all": "All",
        "res.more_filters": "More Filters",
        "btn.filter_items": "Filter by Item",
        "sort.status": "Sort by Status",
        "sort.distance": "Sort by Distance",
        "btn.reset": "Reset",
        "res.filter_pets": "Pet-Friendly",
        "res.filter_baby": "Baby Care",
        "res.filter_wheelchair": "Wheelchair Accessible",
        "res.filter_charging": "Charging Available",
        "btn.traffic": "Toggle Traffic",
        "res.no_stations_map": "No stations match your filters.",
        "common.loading": "Loading...",
        "res.no_stations_list": "No stations found.",
        "res.filter_title": "Filter by Item",
        "nav.resident": "Resident",
        "nav.links": "Links",
        "nav.me": "Me",
        "nav.my_stations": "My Stations",
        "nav.volunteer": "Volunteer",
        "nav.logistics": "Logistics",
        "me.title": "My Profile",
        "station.managed_station_id": "Managed Station ID",
        "btn.signout": "Sign Out",
        "me.login_desc": "Log in to save favorites and contribute.",
        "btn.signin": "Sign In with Google",
        "admin.global_alert_broadcast": "Global Alert Broadcast",
        "admin.alert_placeholder": "Enter a global alert message",
        "admin.publish_alert": "Publish Alert",
        "me.my_stations": "My Stations",
        "me.saved_stations": "Saved Stations",
        "me.no_saved": "You haven't saved any stations yet.",
        "btn.directions": "Directions",
        "btn.call": "Call",
        "station.needs_label": "Needs",
        "station.remarks_label": "Remarks",
        "station.offerings_label": "Offerings",
        "station.login_to_view": "Please log in to view your stations.",
        "station.edit_station": "Edit Station",
        "btn.save": "Save",
        "station.name": "Station Name",
        "station.address_location": "Address & Location",
        "station.use_current_location": "Use Current Location",
        "station.hide_map": "Hide Map",
        "station.pick_on_map": "Pick on Map",
        "station.map_helper_text": "Drag marker or click to set location",
        "station.status": "Status",
        "station.add_needs": "Add Needs",
        "btn.save_changes": "Save Changes",
        "btn.cancel": "Cancel",
        "station.manage_desc": "Manage your station's details, status, and inventory.",
        "btn.edit": "Edit",
        "station.no_owned_stations": "You do not own or manage any stations.",
        "station.create_station_prompt": "Create a new station to get started.",
        "links.tg_title": "Telegram Groups",
        "links.web_title": "Websites",
        "type.supply": "Supply",
        "type.shelter": "Shelter",
        "type.closed": "Closed",
        "type.pet_shelter": "Pet Shelter",
        "type.food_distribution": "Food",
        "type.medical": "Medical",
        "type.collection_point": "Collection",
        "crowd.low": "Low",
        "crowd.medium": "Medium",
        "crowd.high": "High",
        "crowd.full": "Full",
        "FOOD": "Food",
        "DRINKS": "Drinks",
        "MEDICAL_SUPPLIES": "Medical Supplies",
        "HYGIENE": "Hygiene",
        "CLOTHING": "Clothing",
        "BABY_CARE": "Baby Care",
        "PET_SUPPLIES": "Pet Supplies",
        "ELECTRONICS": "Electronics",
        "SHELTER": "Shelter",
        "SERVICES": "Services",
        "favorite.update_failed": "Failed to update favorite",
        "volunteer.data_load_error": "Failed to load volunteer data",
        "volunteer.unknown_station": "Unknown Station",
        "volunteer.task_claimed": "Task claimed!",
        "volunteer.claim_failed": "Failed to claim task",
        "volunteer.confirm_completion": "Confirm delivery completion?",
        "volunteer.task_completed": "Task completed!",
        "volunteer.complete_failed": "Failed to complete task",
        "volunteer.tasks": "Tasks",
        "volunteer.stations": "Stations",
        "volunteer.help_community": "Help your community",
        "volunteer.open_tasks": "Open Tasks",
        "volunteer.my_tasks": "My Tasks",
        "volunteer.my_active_tasks": "Your Active Tasks",
        "volunteer.in_progress": "IN PROGRESS",
        "volunteer.complete": "Complete",
        "volunteer.available_tasks": "Available Tasks",
        "volunteer.no_tasks": "No tasks currently available.",
        "volunteer.posted": "Posted",
        "volunteer.from": "From",
        "volunteer.to": "To",
        "volunteer.volunteer_for_task": "Volunteer for this Task",
        
        // Categories
        "cat.manpower": "Manpower",
        "cat.warmth": "Warmth",
        "cat.food_water": "Food & Water",
        "cat.hygiene_wash": "Hygiene & Wash",
        "cat.electronics": "Electronics",
        "cat.bedding": "Bedding",
        "cat.sanitary": "Sanitary",
        "cat.pets": "Pet Supplies",
        "cat.baby": "Baby Supplies",
        "cat.others": "Others",

        // Items
        "一般義工": "General Volunteers",
        "醫護人員": "Medic",
        "社工": "Social Worker",
        "車手": "Driver",
        "心理輔導員": "Psychological Counselor",
        "保暖內衣": "Thermal Underwear",
        "求毛氈": "Blanket",
        "反光錫紙": "Reflective Foil",
        "熱水": "Hot Water",
        "水": "Water",
        "麵包": "Bread",
        "能量啫喱": "Energy Gel",
        "大毛巾": "Large Towel",
        "洗頭水": "Shampoo",
        "沐浴露": "Body Wash",
        "垃圾袋": "Trash Bag",
        "摺凳": "Folding Stool",
        "番梘": "Soap",
        "尿袋": "Power Bank",
        "照明用品": "Lighting",
        "差電線": "Charging Cable",
        "床墊": "Mattress",
        "枕頭": "Pillow",
        "被": "Quilt",
        "眼罩": "Eye Mask",
        "耳塞": "Earplugs",
        "75%支裝酒精": "75% Alcohol",
        "濕紙巾": "Wet Wipes",
        "女性用品": "Feminine Hygiene",
        "貓狗罐頭": "Pet Canned Food",
        "貓狗乾糧": "Pet Dry Food",
        "寵物衣服": "Pet Clothes",
        "藥品": "Medicine",
        "奶樽": "Baby Bottle",
        "奶粉": "Milk Powder",
        "尿片": "Diapers",
        "文具": "Stationery",
        "紅白藍膠袋": "RB Bag",
        "大聲公": "Megaphone",
        
        // Old items kept for compatibility
        "住宿": "Accommodation",
        "暫住": "Temporary Shelter",
        "宿位": "Beds",
        "庇護中心": "Shelter Center",
        "休息處": "Rest Area",
        "洗澡設施": "Shower Facilities",
        "洗手間": "Toilets",
        "水機": "Water Dispenser",
        "廚房": "Kitchen",
        "食物": "Food",
        "飲品": "Drinks",
        "樽裝水": "Bottled Water",
        "乾糧": "Dry Food",
        "杯麵": "Cup Noodles",
        "熱食": "Hot Food",
        "能量棒": "Energy Bar",
        "湯水": "Soup",
        "罐頭": "Canned Food",
        "餐具": "Cutlery",
        "飯盒": "Lunch Box",
        "紙杯": "Paper Cup",
        "保暖物資": "Warmth Supplies",
        "毛巾": "Towel",
        "毛氈": "Blanket",
        "被鋪": "Bedding",
        "褸": "Coat",
        "襪": "Socks",
        "暖包": "Heat Pack",
        "睡袋": "Sleeping Bag",
        "地墊": "Mat",
        "露營帳篷": "Tent",
        "Heat tech": "Heat Tech",
        "牙刷": "Toothbrush",
        "牙膏": "Toothpaste",
        "口罩": "Mask",
        "豬咀": "Gas Mask",
        "濾罐": "Filter",
        "BB尿片": "Baby Diapers",
        "成人尿片": "Adult Diapers",
        "清潔用品": "Cleaning Supplies",
        "紙巾": "Tissue",
        "一次性內衣褲": "Disposable Underwear",
        "拖鞋": "Slippers",
        "內衣褲": "Underwear",
        "衛生用品": "Sanitary Supplies",
        "N95": "N95 Mask",
        "叉電線": "Charging Cable",
        "火牛": "Adapter",
        "拖板": "Power Strip",
        "電池": "Battery",
        "電筒": "Flashlight",
        "SIM Card": "SIM Card",
        "急救": "First Aid",
        "急救包": "First Aid Kit",
        "輪椅": "Wheelchair",
        "寵物氧氣機": "Pet Oxygen Machine",
        "寵物飛機籠": "Pet Crate",
        "寵物暫托家庭": "Pet Foster Home",
        "貓糧": "Cat Food",
        "狗糧": "Dog Food",
        "獸醫服務": "Vet Service",
        "寵物救援": "Pet Rescue",
        "看顧長者": "Elderly Care",
        "兒童暫託": "Child Care",
        "心理支援": "Psychological Support"
    },
    zh: {
        "welcome_title": "大埔救急 - 確保每分民間力量都用得其所",
        "welcome_subtitle": "一個針對為受大埔宏福苑火災影響嘅街坊同救援義工而設嘅即時資訊整合平台",
        "welcome_resident_title": "歡迎",
        "welcome_resident_subtitle": "作為居民，您可以：",
        "resident_point_1": "搵最近你嘅物資站。",
        "resident_point_2": "根據所需物資filter物資站",
        "resident_point_3": "登入之後可以save低物資站",
        "welcome_volunteer_title": "歡迎",
        "welcome_volunteer_subtitle": "您的幫助至關重要。您可以：",
        "volunteer_point_1": "睇到每個物資站嘅狀態",
        "volunteer_point_2": "根據自己手上有嘅物資搵下有邊度需要",
        "volunteer_point_3": "同多啲居民講呢一個app",
        "welcome_driver_title": "歡迎",
        "welcome_driver_subtitle": "您的車輛可以發揮巨大作用：",
        "driver_point_1": "尋找運輸任務以運送物資。",
        "driver_point_2": "接受適合您車型和路線的任務。",
        "welcome_station_manager_title": "歡迎站長",
        "welcome_station_manager_subtitle": "您是您站點成功的關鍵：",
        "station_manager_point_1": "管理您站點的詳細資訊、狀態和庫存。",
        "station_manager_point_2": "為您的站點團隊創建任務。",
        "station_manager_point_3": "向居民廣播警報。",
        "welcome_admin_title": "歡迎",
        "welcome_admin_subtitle": "系統概覽：",
        "admin_point_1": "管理所有使用者、站點和任務。",
        "admin_point_2": "查看分析和系統健康狀況。",
        "admin_point_3": "處理高層級配置和警報。",
        "get_started": "開始",
        "next": "下一步",
        "back": "返回",
        "what_brings_you_here": "您嚟呢度想做咩？",
        "i_need_help": "我要搵物資",
        "find_supplies": "搵附近嘅物資站同支援。",
        "or_i_want_to_help": "或者我想幫手",
        "i_want_to_volunteer": "我想幫手",
        "join_teams": "支援大埔宏福苑火災影響嘅街坊",
        "i_am_a_driver": "我係車手",
        "help_transport": "幫助在站點之間運輸物資。",
        "back_to_role_selection": "返回",
        "add.title": "新增站點",
        "add.name": "站點名稱",
        "add.placeholder_name": "例如：大埔社區會堂",
        "add.address": "地址",
        "add.placeholder_address": "輸入地址或使用地圖",
        "add.type": "站點類型",
        "add.contact": "聯絡電話",
        "add.placeholder_contact": "可選電話號碼",
        "add.contact_link": "聯絡連結",
        "add.placeholder_contact_link": "可選 URL（例如：Telegram、WhatsApp）",
        "add.source_url": "資訊來源 URL",
        "add.placeholder_source": "資訊來源連結",
        "btn.submit": "提交站點",
        "btn.deselect_all": "全部取消",
        "btn.select_all": "全選",
        "btn.clear": "清除",
        "btn.apply": "套用",
        "btn.add_item": "新增一個新項目",
        "validation.enter_item": "請輸入項目名稱。",
        "validation.no_category": "請選擇一個類別。",
        "validation.already_exists": "此項目已存在。",
        "btn.add": "新增",
        "btn.add_category": "新增一個新類別",
        "validation.enter_category": "請輸入類別名稱。",
        "status.available": "✅ 充足",
        "status.low_stock": "⚠️ 尚需",
        "status.urgent": "‼️ 急需",
        "status.no_data": "🤨 無資料",
        "status.gov_control": "🙅🏻 政府已接手 不需義工物資",
        "status.paused": "暫停接收物資（現場提供）",
        "auth.login_required": "請登入以執行此操作。",
        "vote.success": "投票已成功提交。",
        "vote.error": "提交投票失敗。",
        "favorite.added": "已新增至我的最愛。",
        "favorite.removed": "已從我的最愛中移除。",
        "res.my_location": "我的位置",
        "status.unverified": "未驗證",
        "card.offerings": "提供",
        "card.no_info": "沒有資訊",
        "res.view_details": "查看詳情",
        "res.search_placeholder": "搜尋站點或物品",
        "type.all": "全部",
        "res.more_filters": "更多篩選",
        "btn.filter_items": "按物品篩選",
        "sort.status": "按狀態排序",
        "sort.distance": "按距離排序",
        "btn.reset": "重設",
        "res.filter_pets": "寵物友善",
        "res.filter_baby": "嬰兒護理",
        "res.filter_wheelchair": "無障礙通道",
        "res.filter_charging": "充電服務",
        "btn.traffic": "切換交通狀況",
        "res.no_stations_map": "沒有符合您篩選條件的站點。",
        "common.loading": "載入中...",
        "res.no_stations_list": "找不到站點。",
        "res.filter_title": "按物品篩選",
        "nav.resident": "居民",
        "nav.links": "連結",
        "nav.me": "我",
        "nav.my_stations": "我的站點",
        "nav.volunteer": "志願者",
        "nav.logistics": "物流",
        "me.title": "我的個人資料",
        "station.managed_station_id": "管理的站點 ID",
        "btn.signout": "登出",
        "me.login_desc": "登入以儲存我的最愛和貢獻。",
        "btn.signin": "使用 Google 登入",
        "admin.global_alert_broadcast": "全域警報廣播",
        "admin.alert_placeholder": "輸入全域警報訊息",
        "admin.publish_alert": "發佈警報",
        "me.my_stations": "我的站點",
        "me.saved_stations": "已儲存的站點",
        "me.no_saved": "您尚未儲存任何站點。",
        "btn.directions": "路線",
        "station.needs_label": "需求",
        "station.remarks_label": "備註",
        "station.offerings_label": "提供",
        "station.login_to_view": "請登入以查看您的站點。",
        "station.edit_station": "編輯站點",
        "btn.call": "致電",
        "btn.save": "儲存",
        "station.name": "站點名稱",
        "station.address_location": "地址和位置",
        "station.use_current_location": "使用目前位置",
        "station.hide_map": "隱藏地圖",
        "station.pick_on_map": "在地圖上選擇",
        "station.map_helper_text": "拖曳標記或點擊以設定位置",
        "station.status": "狀態",
        "station.add_needs": "新增需求",
        "btn.save_changes": "儲存變更",
        "btn.cancel": "取消",
        "station.manage_desc": "管理您站點的詳細資訊、狀態和庫存。",
        "btn.edit": "編輯",
        "station.no_owned_stations": "您沒有擁有或管理任何站點。",
        "station.create_station_prompt": "建立一個新站點以開始。",
        "links.tg_title": "Telegram 群組",
        "links.web_title": "網站",
        "type.supply": "物資",
        "type.shelter": "住宿/庇護",
        "type.closed": "已清場",
        "type.pet_shelter": "寵物庇護所",
        "type.food_distribution": "食物",
        "type.medical": "醫療",
        "type.collection_point": "收集點",
        "crowd.low": "低",
        "crowd.medium": "中",
        "crowd.high": "高",
        "crowd.full": "滿",
        "FOOD": "食物",
        "DRINKS": "飲品",
        "MEDICAL_SUPPLIES": "醫療用品",
        "HYGIENE": "衛生用品",
        "CLOTHING": "衣物",
        "BABY_CARE": "嬰兒用品",
        "PET_SUPPLIES": "寵物用品",
        "ELECTRONICS": "電子產品",
        "SHELTER": "庇護所",
        "SERVICES": "服務",
        "favorite.update_failed": "更新我的最愛失敗",
        "volunteer.data_load_error": "載入志願者資料失敗",
        "volunteer.unknown_station": "未知站點",
        "volunteer.task_claimed": "已領取任務！",
        "volunteer.claim_failed": "領取任務失敗",
        "volunteer.confirm_completion": "確認完成運送？",
        "volunteer.task_completed": "任務已完成！",
        "volunteer.complete_failed": "完成任務失敗",
        "volunteer.tasks": "任務",
        "volunteer.stations": "站點",
        "volunteer.help_community": "幫助您的社區",
        "volunteer.open_tasks": "開放任務",
        "volunteer.my_tasks": "我的任務",
        "volunteer.my_active_tasks": "您目前的任務",
        "volunteer.in_progress": "進行中",
        "volunteer.complete": "完成",
        "volunteer.available_tasks": "可領取的任務",
        "volunteer.no_tasks": "目前沒有可領取的任務。",
        "volunteer.posted": "發佈於",
        "volunteer.from": "從",
        "volunteer.to": "到",
        "volunteer.volunteer_for_task": "為此任務擔任志願者",

        // Categories
        "cat.manpower": "人手",
        "cat.warmth": "保暖用品",
        "cat.food_water": "糧食&水",
        "cat.hygiene_wash": "梳洗用品",
        "cat.electronics": "電器",
        "cat.bedding": "寢室用品",
        "cat.sanitary": "衛生用品",
        "cat.pets": "寵物用品",
        "cat.baby": "BB用品",
        "cat.others": "其他",

        // Items
        "一般義工": "一般義工",
        "醫護人員": "醫護人員",
        "社工": "社工",
        "車手": "車手",
        "心理輔導員": "心理輔導員",
        "保暖內衣": "保暖內衣",
        "求毛氈": "求毛氈",
        "反光錫紙": "反光錫紙",
        "熱水": "熱水",
        "水": "水",
        "麵包": "麵包",
        "能量啫喱": "能量啫喱",
        "大毛巾": "大毛巾",
        "洗頭水": "洗頭水",
        "沐浴露": "沐浴露",
        "垃圾袋": "垃圾袋",
        "摺凳": "摺凳",
        "番梘": "番梘",
        "尿袋": "尿袋",
        "照明用品": "照明用品",
        "差電線": "差電線",
        "床墊": "床墊",
        "枕頭": "枕頭",
        "被": "被",
        "眼罩": "眼罩",
        "耳塞": "耳塞",
        "75%支裝酒精": "75%支裝酒精",
        "濕紙巾": "濕紙巾",
        "女性用品": "女性用品",
        "貓狗罐頭": "貓狗罐頭",
        "貓狗乾糧": "貓狗乾糧",
        "寵物衣服": "寵物衣服",
        "藥品": "藥品",
        "奶樽": "奶樽",
        "奶粉": "奶粉",
        "尿片": "尿片",
        "文具": "文具",
        "紅白藍膠袋": "紅白藍膠袋",
        "大聲公": "大聲公",
        
        // Old items kept for compatibility
        "住宿": "住宿",
        "暫住": "暫住",
        "宿位": "宿位",
        "庇護中心": "庇護中心",
        "休息處": "休息處",
        "洗澡設施": "洗澡設施",
        "洗手間": "洗手間",
        "水機": "水機",
        "廚房": "廚房",
        "食物": "食物",
        "飲品": "飲品",
        "樽裝水": "樽裝水",
        "乾糧": "乾糧",
        "杯麵": "杯麵",
        "熱食": "熱食",
        "能量棒": "能量棒",
        "湯水": "湯水",
        "罐頭": "罐頭",
        "餐具": "餐具",
        "飯盒": "飯盒",
        "紙杯": "紙杯",
        "保暖物資": "保暖物資",
        "毛巾": "毛巾",
        "毛氈": "毛氈",
        "被鋪": "被鋪",
        "褸": "褸",
        "襪": "襪",
        "暖包": "暖包",
        "睡袋": "睡袋",
        "地墊": "地墊",
        "露營帳篷": "露營帳篷",
        "Heat tech": "Heat tech",
        "牙刷": "牙刷",
        "牙膏": "牙膏",
        "口罩": "口罩",
        "豬咀": "豬咀",
        "濾罐": "濾罐",
        "BB尿片": "BB尿片",
        "成人尿片": "成人尿片",
        "清潔用品": "清潔用品",
        "紙巾": "紙巾",
        "一次性內衣褲": "一次性內衣褲",
        "拖鞋": "拖鞋",
        "內衣褲": "內衣褲",
        "衛生用品": "衛生用品",
        "N95": "N95",
        "叉電線": "叉電線",
        "火牛": "火牛",
        "拖板": "拖板",
        "電池": "電池",
        "電筒": "電筒",
        "SIM Card": "SIM Card",
        "急救": "急救",
        "急救包": "急救包",
        "輪椅": "輪椅",
        "寵物氧氣機": "寵物氧氣機",
        "寵物飛機籠": "寵物飛機籠",
        "寵物暫托家庭": "寵物暫托家庭",
        "貓糧": "貓糧",
        "狗糧": "狗糧",
        "獸醫服務": "獸醫服務",
        "寵物救援": "寵物救援",
        "看顧長者": "看顧長者",
        "兒童暫託": "兒童暫託",
        "心理支援": "心理支援"
    }
};

type Language = 'en' | 'zh';

interface LanguageContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({
    children
}: {
    children: ReactNode
}) => {
    const [language, setLanguage] = useState<Language>('zh');

    const t = (key: keyof typeof translations.en) => {
        return translations[language][key] || translations.en[key];
    };

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t
        }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
